// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//   protoc-gen-go v1.30.0
//   protoc        (your version here)
// source: internal/proto/task.proto

package proto

import (
	_ "google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

type Task struct {
	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpressionId int32  `protobuf:"varint,2,opt,name=expression_id,json=expressionId,proto3" json:"expression_id,omitempty"`
	Operation    string `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Arg1         string `protobuf:"bytes,4,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2         string `protobuf:"bytes,5,opt,name=arg2,proto3" json:"arg2,omitempty"`
}

type ResultRequest struct {
	Id     int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
}

type TaskResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

type Empty struct{}